import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/app/components/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfoio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr-FR">
      <body className={inter.className}>
      <Provider>{children}</Provider>
      </body>
    </html>
  )
}